"""
設定ファイル例
実際の認証情報は config.py に記載してください（Gitにコミットしないこと）
"""

# Google Cloud 認証
GOOGLE_APPLICATION_CREDENTIALS = "service_account.json"

# クローラー設定
CRAWLER_VIEWPORT_WIDTH = 1920
CRAWLER_VIEWPORT_HEIGHT = 1080
CRAWLER_WAIT_TIME = 2  # 秒

# PDF設定
PDF_DPI = 300

# クラスタリング設定
CLUSTERING_OVERLAP_THRESHOLD = 0.7
CLUSTERING_VERTICAL_GAP_MULTIPLIER = 2.5
CLUSTERING_MIN_VERTICAL_GAP = 80
CLUSTERING_HORIZONTAL_GAP = 10
CLUSTERING_ORPHAN_AREA_THRESHOLD = 0.1
CLUSTERING_ORPHAN_DISTANCE_THRESHOLD = 200

# 出力設定
OUTPUT_DIR = "output_data"
TEMP_DIR = "temp"

